### ISSUE TITLE
Unable to authenticate in mitaka version

### ISSUE THREAD

**Issue by omkartelee08** [hambuergaer/ceilometer_python_monthly_report#1]
I am getting following error.

AuthorizationFailure: Authorization Failed: The resource could not be found. (HTTP 404)

**Comment by welkson** [comment]
same problem here (Mitaka via Fuel 9)

root@sm-ctrl01:~/ceilometer_python_monthly_report# python ceilometer_monthly_report.py 
Traceback (most recent call last):
  File "ceilometer_monthly_report.py", line 181, in <module>
    get_statistics_per_instance()
  File "ceilometer_monthly_report.py", line 70, in get_statistics_per_instance
    get_keystone_tenants()
  File "ceilometer_monthly_report.py", line 45, in get_keystone_tenants
    keystone = kclient.Client(**get_keystone_creds(args.os_auth_url,args.os_username,args.os_password,args.os_tenant_name))
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 166, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/dist-packages/positional/__init__.py", line 94, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 584, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 210, in get_raw_token_from_identity_service
    _("Authorization Failed: %s") % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization Failed: The resource could not be found. (HTTP 404)

**Comment by hambuergaer** [comment]
Hi, this script was engineered for OpenStack 6 (Juno). Unfortunately I don`t have a current Openstack version in place. So please feel free to fork this script and take as a basis for the development on your running Openstack version.
